package: d2u_news
version: '1.1.7'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_news

page:
    title: 'translate:d2u_news'
    perm: 'd2u_news[]'
    icon: rex-icon fa-newspaper-o
    subpages:
        news: { title: 'translate:d2u_news_news_title', icon: rex-icon fa-newspaper-o }
        categories: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemClass: pull-right, perm: 'd2u_news[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemClass: pull-right, perm: 'd2u_news[settings]' }

requires:
    php: '>=8.0'
    redaxo: '>=5.10.0'
    packages:
        d2u_helper: '>=1.14.0'
        sprog: '>=1.0.0'

conflicts:
    packages:
        d2u_courses: '<3.5.0'

default_config:
    default_sort: 'name'

installer_ignore:
    - .github