package: d2u_news
version: '1.1.1'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_news

page:
    title: 'translate:d2u_news'
    perm: d2u_news[]
    icon: rex-icon fa-newspaper-o
    subpages:
        news: { title: 'translate:d2u_news_news_title', icon: rex-icon fa-newspaper-o }
        categories: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: d2u_news[settings] }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_news[settings] }

requires:
    packages:
        d2u_helper: '>=1.4.3'
        sprog: '>=1.0.0'