package: d2u_news
version: '1.0.2'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_news

page:
    title: 'translate:d2u_news'
    perm: d2u_news[]
    icon: rex-icon fa-newspaper-o
    subpages:
        news: { title: 'translate:d2u_news_news_title', icon: rex-icon fa-newspaper-o }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: d2u_news[settings] }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_news[settings] }

requires:
    redaxo: '>=5.3.0'
    packages:
        d2u_helper: '>=1.3.2'
        sprog: '>=1.0.0'
        url: '>=1.0.1'
        yrewrite: '>=2.0.1'